# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-25 00:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthcard',
            name='default_bid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
